# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from register import Ui_RegisterWindow
from admin import Ui_Market
from mainwindow import MainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(31, 42, 58);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_login_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login_name.setGeometry(QtCore.QRect(235, 180, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lineEdit_login_name.setFont(font)
        self.lineEdit_login_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #000000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);}")
        self.lineEdit_login_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_login_name.setObjectName("lineEdit_login_name")
        self.lineEdit_login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login_password.setGeometry(QtCore.QRect(235, 250, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lineEdit_login_password.setFont(font)
        self.lineEdit_login_password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #000000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);}")
        self.lineEdit_login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_login_password.setDragEnabled(False)
        self.lineEdit_login_password.setReadOnly(False)
        self.lineEdit_login_password.setObjectName("lineEdit_login_password")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(300, 340, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    background-color: rgb(244, 104, 104);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(207, 88, 88);\n"
"}\n"
"    ")
        self.pushButton_login.setObjectName("pushButton_login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 420, 220, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat Thin")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_register = QtWidgets.QPushButton(self.centralwidget)
        self.label_register.setGeometry(QtCore.QRect(480, 420, 69, 25))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(9)
        self.label_register.setFont(font)
        self.label_register.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 255, 133);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(207, 88, 88);\n"
"}")
        self.label_register.setObjectName("label_register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat Thin")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_login_name.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_login_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_login.setText(_translate("MainWindow", "Login!"))
        self.label.setText(_translate("MainWindow", "If you don\'t have an account?"))
        self.label_register.setText(_translate("MainWindow", "Register!"))
        self.pushButton_login.clicked.connect(lambda: self.login())
        self.label_register.clicked.connect(lambda: self.OpenRegWindow())
    def login(self):
        self.name = self.lineEdit_login_name.text()
        self.password = self.lineEdit_login_password.text()
        if len(self.name) == 0 or len(self.password) == 0:
            self.statusBar.showMessage("Please input all fields.")
        elif self.name == "admin" and self.password == "12345":
            print("Successfully in.")
            self.OpenAdminWindow()

        else:
            conn = sqlite3.connect("users.db")
            cur = conn.cursor()
            query = 'SELECT password FROM clients WHERE name =\'' + self.name + "\'"
            cur.execute(query)
            result_pass = cur.fetchone()[0]
            if result_pass == self.password:
                print("Successfully logged in.")
                self.OpenMainWindow()
                MainWindow.close()
            else:
                self.statusBar.showMessage("Invalid username or password")



    def OpenRegWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_RegisterWindow()
        self.ui.setupUi(self.window)
        self.window.show()



    def OpenAdminWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Market()
        self.ui.setupUi(self.window)
        self.window.show()
        self.CLO()
    def OpenMainWindow(self):
        import sys

        from PySide6.QtWidgets import QApplication

        from mainwindow import MainWindow

        if __name__ == '__main__':
            app = QApplication()
            window = MainWindow()
            window.show()
            self.a = tuple(self.name)
            for i in self.a:
                self.o = i
                break
            a = "0"
            window.ui.label_profile_bought.setText(a)
            window.ui.label_profile_name.setText(self.name)
            window.ui.lineEdit_old_pass.setText(self.password)
            window.ui.btn_profile.setText(self.o)
            self.CLO()
            sys.exit(app.exec_())

    def CLO(self):
        MainWindow.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
