# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_RegisterWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(31, 42, 58);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_reg_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_reg_name.setGeometry(QtCore.QRect(235, 180, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lineEdit_reg_name.setFont(font)
        self.lineEdit_reg_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #000000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);}")
        self.lineEdit_reg_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_reg_name.setObjectName("lineEdit_reg_name")
        self.lineEdit_reg_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_reg_password.setGeometry(QtCore.QRect(235, 250, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lineEdit_reg_password.setFont(font)
        self.lineEdit_reg_password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #000000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);}")
        self.lineEdit_reg_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_reg_password.setDragEnabled(False)
        self.lineEdit_reg_password.setReadOnly(False)
        self.lineEdit_reg_password.setObjectName("lineEdit_reg_password")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(300, 400, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("QPushButton{\n"
"    background-color: rgb(244, 104, 104);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(207, 88, 88);\n"
"}\n"
"    ")
        self.pushButton_register.setObjectName("pushButton_register")
        self.lineEdit_reg_confirm_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_reg_confirm_password.setGeometry(QtCore.QRect(235, 320, 330, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(12)
        self.lineEdit_reg_confirm_password.setFont(font)
        self.lineEdit_reg_confirm_password.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 20px;\n"
"    color: #000000;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(48, 50, 62);}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 170, 255);}")
        self.lineEdit_reg_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_reg_confirm_password.setDragEnabled(False)
        self.lineEdit_reg_confirm_password.setReadOnly(False)
        self.lineEdit_reg_confirm_password.setObjectName("lineEdit_reg_confirm_password")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Montserrat Thin")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_reg_name.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_reg_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_register.setText(_translate("MainWindow", "Register!"))
        self.lineEdit_reg_confirm_password.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.pushButton_register.clicked.connect(lambda: self.register())
        self.pushButton_register.clicked.connect(lambda: self.OpenMainWindow())
        self.pushButton_register.clicked.connect(lambda: MainWindow.close())
    def register(self):
        self.name = self.lineEdit_reg_name.text()
        self.password = self.lineEdit_reg_password.text()
        self.con_password = self.lineEdit_reg_confirm_password.text()
        if len(self.name) == 0 or len(self.password) == 0 or len(self.con_password) == 0:
            self.statusBar.showMessage("Please fill in all inputs.")

        elif self.password != self.con_password :
            self.statusBar.showMessage("Passwords do not match.")
        elif len(self.password) < 8:
            self.statusBar.showMessage("Passwords is so short.")

        else:


            self.con = sqlite3.connect("users.db")
            self.cur = self.con.cursor()


            self.client_info = (self.name, self.password)
            self.cur.execute("""INSERT INTO clients VALUES (NULL,?,?)""", (self.client_info))

            self.con.commit()
            self.con.close()

    def OpenMainWindow(self):
        import sys

        from PySide6.QtWidgets import QApplication

        from mainwindow import MainWindow

        if __name__ == '__main__':
            app = QApplication()
            window = MainWindow()
            window.show()
            self.a = tuple(self.name)
            for i in self.a:
                self.o = i
                break
            a = "0"
            window.ui.label_profile_bought.setText(a)
            window.ui.label_profile_name.setText(self.name)
            window.ui.lineEdit_old_pass.setText(self.password)
            window.ui.btn_profile.setText(self.o)
            sys.exit(app.exec_())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
